# action.yml
name: "Rust Test Results Formatter"
description: "Formats Rust test results into a pretty GitHub Actions Job Summary"
author: "Petr Gadorek (hahihula@gmail.com)"

inputs:
  results-file:
    description: "Path to the test results file"
    required: true
    default: "result.txt"

runs:
  using: "node20"
  main: "src/index.js"

branding:
  icon: "check-circle"
  color: "green"
